//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NET_DBFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int C_EmployeeId { get; set; }
        public string C_Name { get; set; }
        public string C_Gender { get; set; }
        public string C_City { get; set; }
        public Nullable<decimal> C_Salary { get; set; }
    }
}
